# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PROYECTO_BRAZO.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GUARDAR = QtWidgets.QPushButton(self.centralwidget)
        self.GUARDAR.setGeometry(QtCore.QRect(350, 350, 93, 28))
        self.GUARDAR.setObjectName("GUARDAR")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 290, 711, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(60)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Garra = QtWidgets.QSlider(self.widget)
        self.Garra.setMaximum(9)
        self.Garra.setOrientation(QtCore.Qt.Horizontal)
        self.Garra.setObjectName("Garra")
        self.horizontalLayout.addWidget(self.Garra)
        self.Brazo1 = QtWidgets.QSlider(self.widget)
        self.Brazo1.setMaximum(9)
        self.Brazo1.setOrientation(QtCore.Qt.Horizontal)
        self.Brazo1.setObjectName("Brazo1")
        self.horizontalLayout.addWidget(self.Brazo1)
        self.Brazo2 = QtWidgets.QSlider(self.widget)
        self.Brazo2.setMaximum(9)
        self.Brazo2.setOrientation(QtCore.Qt.Horizontal)
        self.Brazo2.setObjectName("Brazo2")
        self.horizontalLayout.addWidget(self.Brazo2)
        self.Base = QtWidgets.QSlider(self.widget)
        self.Base.setMaximum(9)
        self.Base.setOrientation(QtCore.Qt.Horizontal)
        self.Base.setObjectName("Base")
        self.horizontalLayout.addWidget(self.Base)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GUARDAR.setText(_translate("MainWindow", "GUARDAR"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
